# Datan analysointi K2021 - Tehtävät kerta 3

Palauta ratkaisusi Moodleen, kun olet ensin testannut ratkaisusi toimivuuden Notebookilla tai omalla koneellasi. Kun olet palauttanut tehtäväsi Moodleen, ne arvioidaan pistein:
* 1,0 p. Vastaus oikein ensimmäisellä yrityksellä.
* 0,5 p. Vastaus oikein toisella yrityksellä.
* 0 p. Vastaus väärin kolmannella yrityksellä.

**Tee tehtävät ilman for-silmukoita tms.**

### 1. Päästöjen aiheuttajia

Tee funktio emissions(url), joka tekee järjestyksessä seuraavaa:
* lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
* tallentaa DataFrameen sarakkeet 'country' ja 'main activity sector name',
* poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'
* laskee kuinka monta kertaa sarakkeen 'main activity sector name' eri arvot esiintyvät DataFramessa,
* tulostaa (viisi ensimmäistä riviä) järjestyksessä pienimmästä suurimpaan sarakkeen 'main activity sector name' arvojen lukumäärät.

Tässä tehtävässä url=https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv

Esimerkiksi, emissions(url) tulostaa:

| | | |
|:---|:---|:---|
|45 |Capture of greenhouse gases under Directive 2009/31/EC      | 14|
|46 |Transport of greenhouse gases under Directive 2009/31/EC    | 22|
|40 |Production of glyoxal and glyoxylic acid                    | 37|
|39 |Production of adipic acid                                   | 43|
|44 |Production of soda ash and sodium bicarbonate               |325|
|Name: sector, dtype: int64| | |

In [ ]:
def emissions(url):
    # Kirjoita vastauksesi tähän
    # ...
    
    # Älä kirjoita muita print komentoja ennen tulos muuttujan tulostusta.
    print(tulos)
    
# Testaa funktiotasi:
url='https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
emissions(url)

In [48]:
import pandas as pd
def emissions(url):
    # Kirjoita vastauksesi tähän
    # ...
    
    #lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
    df = pd.read_csv(url, engine="python", encoding="utf-8-sig", sep="\\t")
    #print(df.head())
    
    #tallentaa DataFrameen sarakkeet 'country' ja 'main activity sector name',
    new_df = df[['"country', 'main activity sector name']].copy()
    #print(new_df.head(60))
    #print(new_df.shape)
    
    #poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'
    indexNames = new_df[(new_df['main activity sector name'] == '20-99 All stationary installations')].index 
    indexNames1 = new_df[(new_df['main activity sector name'] == '21-99 All industrial installations (excl. combustion)')].index 
    new_df.drop(indexNames , inplace=True)
    new_df.drop(indexNames1 , inplace=True)
    #print(new_df.head(60))
    #print(new_df.shape)
    
    #laskee kuinka monta kertaa sarakkeen 'main activity sector name' eri arvot esiintyvät DataFramessa,
    new_df['counts'] = new_df['main activity sector name'].map(new_df['main activity sector name'].value_counts())
    #new_df=new_df.drop_duplicates(subset='main activity sector name', keep="last")

    
    #tulostaa (viisi ensimmäistä riviä) järjestyksessä pienimmästä suurimpaan sarakkeen 'main activity sector name' arvojen lukumäärät.
    
    new_df=new_df.groupby(['main activity sector name']).size().sort_values(ascending=True)
    new_df.index.name = None
    new_df.name = 'sector'
    tulos=new_df.head(5)
    
    
    # Älä kirjoita muita print komentoja ennen tulos muuttujan tulostusta.
    print(tulos)
    
# Testaa funktiotasi:
url='https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
emissions(url)

45 Capture of greenhouse gases under Directive 2009/31/EC       14
46 Transport of greenhouse gases under Directive 2009/31/EC     22
40 Production of glyoxal and glyoxylic acid                     37
39 Production of adipic acid                                    43
44 Production of soda ash and sodium bicarbonate               325
Name: sector, dtype: int64

### 2. Päästöjen summaaminen

Tee funktio emissions(url), joka tekee järjestyksessä seuraavaa:
* lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
* tallentaa DataFrameen sarakkeet 'main activity sector name', 'value' ja 'year',
* poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'
* tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
* laskee uuteen DataFrameen kuinka paljon ovat kokonaispäästöt sektoreittain (summa sarakkeesta 'values', jotka on ryhmitelty sarakkeen 'main activity sector name' mukaan),
* järjestää uuden DataFramen rivit suurimmasta pienimpään sarakkeen 'value' mukaan,
* tulostaa viisi ensimmäistä riviä DataFramesta siten, että sarake 'main activity sector name' on nimetty sarakkeeksi 'sector',
* huomaa, että sarake 'value' on ennen saraketta 'sector'.

Tässä tehtävässä url=https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv

Esimerkiksi, emissions(url) tulostaa:

|   | value        |                   sector             |
|:---|:---|:---|
|1  | 1.273006e+10 |              20 Combustion of fuels  |
|5  | 2.053915e+09 | 24  Production of pig iron or steel  |
|10 | 1.803550e+09 |     29 Production of cement clinker  |
|2  | 1.678130e+09 |         21  Refining of mineral oil  |
|0  | 5.644274e+08 |                         10 Aviation  |

In [ ]:
def emissions(url):
    # Kirjoita vastauksesi tähän
    # ...
    
    
    # Älä kirjoita muita print komentoja ennen tulos muuttujan tulostusta.
    print(tulos)
    
# Testaa funktiotasi:
url='https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
emissions(url)

In [9]:
import pandas as pd
def emissions(url):
    # Kirjoita vastauksesi tähän
    
    #lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t')
    df = pd.read_csv(url, engine="python", encoding="utf-8-sig", sep="\\t")
    #print(df.head())
    
    #tallentaa DataFrameen sarakkeet 'main activity sector name', 'value' ja 'year',
    new_df = df[['main activity sector name', 'value', 'year"' ]].copy()
    #print(new_df.head())
    #print(new_df.shape)
    
    #poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'
    indexNames = new_df[(new_df['main activity sector name'] == '20-99 All stationary installations')].index 
    indexNames1 = new_df[(new_df['main activity sector name'] == '21-99 All industrial installations (excl. combustion)')].index 
    new_df.drop(indexNames , inplace=True)
    new_df.drop(indexNames1 , inplace=True)
    
    #print(new_df.head())
    #print(new_df.shape)
    
    #tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015
    new_df['year"'] = new_df['year"'].str.replace('"','', regex=True)
    new_df = new_df[~new_df['year"'].str.startswith('Total')]
    
    #print(new_df.head(50))
    new_df['year"'] = new_df['year"'].astype(int)
    
    new_df=(new_df[(new_df['year"']>= 2010) & (new_df['year"']<=2015)])
    #print(new_df.head())
    
    #laskee uuteen DataFrameen kuinka paljon ovat kokonaispäästöt sektoreittain (summa sarakkeesta 'values', jotka on ryhmitelty sarakkeen 'main activity sector name' mukaan),
    uusi_Dataframe=new_df.groupby('main activity sector name',as_index=False)['value'].sum()
    uusi_Dataframe.sort_values('main activity sector name')
    #print(uusi_Dataframe.head()) 
    
    #järjestää uuden DataFramen rivit suurimmasta pienimpään sarakkeen 'value' mukaan,
    uusi_Dataframe = uusi_Dataframe.sort_values(by=['value'], ascending=False)
    #print(uusi_Dataframe.head())
    
    #tulostaa viisi ensimmäistä riviä DataFramesta siten, että sarake 'main activity sector name' on nimetty sarakkeeksi 'sector',
    uusi_Dataframe.columns = ['sector', 'value']
    #print(uusi_Dataframe.head())
    
    #huomaa, että sarake 'value' on ennen saraketta 'sector'.
    uusi_Dataframe = uusi_Dataframe[['value','sector']]
    tulos=uusi_Dataframe.head()
    
    # Älä kirjoita muita print komentoja ennen tulos muuttujan tulostusta.
    print(tulos)
    
# Testaa funktiotasi:
url='https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
emissions(url)

           value                               sector
1   1.273006e+10               20 Combustion of fuels
5   2.053915e+09  24  Production of pig iron or steel
10  1.803550e+09      29 Production of cement clinker
2   1.678130e+09          21  Refining of mineral oil
0   5.644274e+08                          10 Aviation

### 3. Päästöjen muutokset vuosittain

Tee funktio emissions(url), joka tekee järjestyksessä seuraavaa:
* lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
* tallentaa DataFrameen sarakkeet 'country_code', 'main activity sector name', 'value' ja 'year',
* poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'
* tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
* laskee uuteen DataFrameen kuinka paljon päästöjä on ollut yhteensä vuosittain (laskee yhteen sarakkeen 'value' arvot, jotka on ryhmitelty sarakkeen 'year' arvojen mukaan),
* laskee uuteen DataFrameen uuteen sarakkeeseen 'change' kuinka paljon päästöt muuttuivat prosentuaalisesti edellisestä vuodesta (huom! vuoden 2010 arvo saa olla NaN, koska vuoden 2009 arvot on suodatettu pois),
* pyöristää em. prosentuaalisen muutoksen yhden desimaalin tarkkuuteen,
* laskee DataFramen uuteen sarakkeeseen 'cumsum' kumulatiivisen päästöjen summan vuodesta 2010 vuoteen 2015,
* tulostaa edellä kuvatulla tavalla tuotetun DataFramen siten, että DataFramen indeksinä on 'year'.

Tässä tehtävässä url=https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv

Esimerkiksi, emissions(url) tulostaa:

| |emissions|  change        |cumsum |
|:---|:---|:---|:---|
|year     |                |       |                |
|2010  		|5.068290e+09  |   NaN | 5.068290e+09   |
|2011  		|3.505169e+09  | -30.8 | 8.573458e+09   |
|2012  		|3.788401e+09  |   8.1 | 1.236186e+10   |
|2013  		|2.833849e+09  | -25.2 | 1.519571e+10   |
|2014  		|2.891243e+09  |   2.0 | 1.808695e+10   |
|2015  		|3.341047e+09  |  15.6 | 2.142800e+10   |

In [ ]:
def emissions(url):
    # Kirjoita vastauksesi tähän
    # ...
    
    # Älä kirjoita muita print komentoja ennen tulos muuttujan tulostusta.
    print(tulos)
    
# Testaa funktiotasi:
url='https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
emissions(url)

In [38]:
def emissions(url):
    # Kirjoita vastauksesi tähän
    # ...
    
    #lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
    df = pd.read_csv(url, engine="python", encoding="utf-8-sig", sep="\\t")
    #print(df.head())
    
    #tallentaa DataFrameen sarakkeet 'country_code', 'main activity sector name', 'value' ja 'year',
    new_df = df[['main activity sector name', 'value', 'year"' ]].copy()
    #print(new_df.head())
    
    #poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'
    indexNames = new_df[(new_df['main activity sector name'] == '20-99 All stationary installations')].index 
    indexNames1 = new_df[(new_df['main activity sector name'] == '21-99 All industrial installations (excl. combustion)')].index 
    new_df.drop(indexNames , inplace=True)
    new_df.drop(indexNames1 , inplace=True)
    
    #print(new_df.head())
    
    #tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
    new_df['year"'] = new_df['year"'].str.replace('"','', regex=True)
    new_df = new_df[~new_df['year"'].str.startswith('Total')]
    
    #print(new_df.head(50))
    new_df['year"'] = new_df['year"'].astype(int)
    
    new_df=(new_df[(new_df['year"']>= 2010) & (new_df['year"']<=2015)])
    #print(new_df.head())
    
    #laskee uuteen DataFrameen kuinka paljon päästöjä on ollut yhteensä vuosittain (laskee yhteen sarakkeen 'value' arvot, jotka on ryhmitelty sarakkeen 'year' arvojen mukaan),
    uusi_Dataframe=new_df.groupby('year"',as_index=False)['value'].sum()
    uusi_Dataframe.sort_values('year"')
    #print(uusi_Dataframe.head()) 
    
    #laskee uuteen DataFrameen uuteen sarakkeeseen 'change' kuinka paljon päästöt muuttuivat prosentuaalisesti edellisestä vuodesta (huom! vuoden 2010 arvo saa olla NaN, koska vuoden 2009 arvot on suodatettu pois),
    uusi_Dataframe['change'] = ((uusi_Dataframe['value'].diff())/uusi_Dataframe['value'].shift())*100
    #print(uusi_Dataframe.head()) 
    
    #pyöristää em. prosentuaalisen muutoksen yhden desimaalin tarkkuuteen,
    decimals = 1  
    uusi_Dataframe['change'] = uusi_Dataframe['change'].apply(lambda x: round(x, decimals))
    #print(uusi_Dataframe.head())
    
    #laskee DataFramen uuteen sarakkeeseen 'cumsum' kumulatiivisen päästöjen summan vuodesta 2010 vuoteen 2015,
    uusi_Dataframe['cumsum']=uusi_Dataframe['value'].cumsum()
    #print(uusi_Dataframe.head())
    
    #tulostaa edellä kuvatulla tavalla tuotetun DataFramen siten, että DataFramen indeksinä on 'year'.
    uusi_Dataframe.columns = ['year', 'emissions', 'change', 'cumsum']
    #print(uusi_Dataframe.head())
    
    uusi_Dataframe.set_index('year', inplace=True)
    #print(uusi_Dataframe.head())
    
    tulos=(uusi_Dataframe.head(6))
    
    # Älä kirjoita muita print komentoja ennen tulos muuttujan tulostusta.
    print(tulos)
    
# Testaa funktiotasi:
url='https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
emissions(url)

         emissions  change        cumsum
year
2010  5.068290e+09     NaN  5.068290e+09
2011  3.505169e+09   -30.8  8.573458e+09
2012  3.788401e+09     8.1  1.236186e+10
2013  2.833849e+09   -25.2  1.519571e+10
2014  2.891243e+09     2.0  1.808695e+10
2015  3.341047e+09    15.6  2.142800e+10

### 4. Suurimmat kokonaispäästöt maittain

Tee funktio emissions(url), joka tekee järjestyksessä seuraavaa:
* lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
* tallentaa DataFrameen sarakkeet 'country_code', 'main activity sector name', 'value' ja 'year',
* poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'
* tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
* laskee uuteen DataFrameen kuinka paljon päästöjä kukin maa on tuottanut minäkin vuonna (laskee yhteen sarakkeen 'value' arvot, jotka on ryhmitelty sarakkeiden 'country_code' ja 'year' mukaan),
* tallentaa uuteen DataFrameen kunkin maan (sarake 'country_code') suurimmat päästöt (sarake 'value') ja päästön tuottamisvuoden (sarake 'year'),
* järjestää em. DataFramen rivit suurimmasta pienimpään sarakkeen 'value' mukaan,
* nimeää sarakkeen 'country_code' sarakkeeksi 'ccode',
* tarvittaessa järjestää sarakkeet järjestykseen 'ccode', 'year', 'value' ja tulostaa viisi ensimmäistä riviä.

**Vinkki:** Tutki tarvittaessa pandasin groupby metodin [kuvausta](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html).

Tässä tehtävässä url=https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv

Esimerkiksi, emissions(url) tulostaa:

| |ccode | year |    value |
|:---|:---|:---|:---|
|30    | DE   |	2010 | 1.298336e+09 |
|66    | GB   |	2010 | 6.420594e+08 |
|50    | ES   |	2012 | 5.579101e+08 |
|150   | PL   |	2010 | 4.605025e+08 |
|102   | IT   |	2010 | 4.505878e+08 |

In [ ]:
def emissions(url):
    # Kirjoita vastauksesi tähän
    # ...
    
    # Älä kirjoita muita print komentoja ennen tulos muuttujan tulostusta.
    print(tulos)
    
# Testaa funktiotasi:
url='https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
emissions(url)

In [133]:
import pandas as pd
def emissions(url):
    # Kirjoita vastauksesi tähän
    # lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
    df = pd.read_csv(url, engine="python", encoding="utf-8-sig", sep="\\t")
    #print(df.head())
    
    #tallentaa DataFrameen sarakkeet 'country_code', 'main activity sector name', 'value' ja 'year',
    new_df = df[['country_code', 'main activity sector name', 'value', 'year"' ]].copy()
    #print(new_df.head())
    
    #poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'
    indexNames = new_df[(new_df['main activity sector name'] == '20-99 All stationary installations')].index 
    indexNames1 = new_df[(new_df['main activity sector name'] == '21-99 All industrial installations (excl. combustion)')].index 
    new_df.drop(indexNames , inplace=True)
    new_df.drop(indexNames1 , inplace=True)
    #print(new_df.head())
    
    #tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
    new_df['year"'] = new_df['year"'].str.replace('"','', regex=True)
    new_df = new_df[~new_df['year"'].str.startswith('Total')]
    
    #print(new_df.head(50))
    new_df['year"'] = new_df['year"'].astype(int)
    
    new_df=(new_df[(new_df['year"']>= 2010) & (new_df['year"']<=2015)])
    #print(new_df.head())
    
    #laskee uuteen DataFrameen kuinka paljon päästöjä kukin maa on tuottanut minäkin vuonna (laskee yhteen sarakkeen 'value' arvot, jotka on ryhmitelty sarakkeiden 'country_code' ja 'year' mukaan),
    uusi_Dataframe=new_df.groupby(["country_code", 'year"'], as_index=False)['value'].sum()
    #print(uusi_Dataframe.head(5))
    uusi_Dataframe = pd.DataFrame(uusi_Dataframe)
    #print(list(uusi_Dataframe.columns))
    
    #tallentaa uuteen DataFrameen kunkin maan (sarake 'country_code') suurimmat päästöt (sarake 'value') ja päästön tuottamisvuoden (sarake 'year'),
    df1=uusi_Dataframe.loc[uusi_Dataframe.groupby('country_code')['value'].idxmax()]
    #print(df1.head(5))
    
    #järjestää em. DataFramen rivit suurimmasta pienimpään sarakkeen 'value' mukaan,
    df1 = df1.sort_values(by=['value'], ascending=False)
    #print(df1.head(5))
    
    #nimeää sarakkeen 'country_code' sarakkeeksi 'ccode',
    df1.columns = ['ccode', 'year', 'value']
    #print(df1.head(5))
    
    #tarvittaessa järjestää sarakkeet järjestykseen 'ccode', 'year', 'value' ja tulostaa viisi ensimmäistä riviä.
    tulos=df1.head(5)
    
    # Älä kirjoita muita print komentoja ennen tulos muuttujan tulostusta.
    print(tulos)
    
# Testaa funktiotasi:
url='https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
emissions(url)

    ccode  year         value
30     DE  2010  1.298336e+09
66     GB  2010  6.420594e+08
50     ES  2012  5.579101e+08
150    PL  2010  4.605025e+08
102    IT  2010  4.505878e+08

### 5. Toiseksi suurimmat kokonaispäästöt maittain

Tee funktio emissions(url), joka tekee järjestyksessä seuraavaa:
* lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
* tallentaa DataFrameen sarakkeet 'country_code', 'main activity sector name', 'value' ja 'year',
* poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'
* tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
* laskee uuteen DataFrameen kuinka paljon päästöjä kukin maa on tuottanut minäkin vuonna (laskee yhteen sarakkeen 'value' arvot, jotka on ryhmitelty sarakkeiden 'country_code' ja 'year' mukaan),

* tallentaa uuteen DataFrameen kunkin maan (sarake 'country_code') **toiseksi** suurimmat päästöt (sarake 'value') ja päästön tuottamisvuoden (sarake 'year'),
* järjestää em. DataFramen rivit suurimmasta pienimpään sarakkeen 'value' mukaan,
* nimeää sarakkeen 'country_code' sarakkeeksi 'ccode',
* tarvittaessa järjestää sarakkeet järjestykseen 'ccode', 'year', 'value' ja tulostaa viisi ensimmäistä riviä.

**Vinkkejä:** 
* Tutki tarvittaessa pandasin [groupby](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html) ja [agg](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.agg.html) metodien kuvauksia.
* Jos käytät pandasin agg metodin argumenttina funktiota, niin tulee funktion sisällä etsiä toiseksi suurin arvo .iloc ominaisuudella (Tämä on tärkeää etenkin tehtävän Moodle palautuksen yhteydessä). 

Tässä tehtävässä url=https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv

Esimerkiksi, emissions(url) tulostaa:

| |ccode | year |    value |
|:---|:---|:---|:---|
|33    | DE  |2013  |1.073414e+09|
|49    | ES  |2011  |5.561922e+08|
|152   | PL  |2012  |4.348634e+08|
|67    | GB  |2011  |4.252068e+08|
|62    | FR  |2012  |3.104471e+08|

In [ ]:
def emissions(url):
    # Kirjoita vastauksesi tähän
    # ...
    
    # Älä kirjoita muita print komentoja ennen tulos muuttujan tulostusta.
    print(tulos)
    
# Testaa funktiotasi:
url='https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
emissions(url)

In [46]:
import pandas as pd
def emissions(url):
    # Kirjoita vastauksesi tähän
    # lataa datan DataFrameen url:sta, jossa eroinmerkkinä on tabulaattori ('\t'),
    df = pd.read_csv(url, engine="python", encoding="utf-8-sig", sep="\\t")
    #print(df.head())
    
    #tallentaa DataFrameen sarakkeet 'country_code', 'main activity sector name', 'value' ja 'year',
    new_df = df[['country_code', 'main activity sector name', 'value', 'year"' ]].copy()
    #print(new_df.head())
    
    #poistaa DataFramesta rivit, jos sarakkeessa 'main activity sector name' esiintyy merkkijonot '20-99 All stationary installations' tai '21-99 All industrial installations (excl. combustion)'
    indexNames = new_df[(new_df['main activity sector name'] == '20-99 All stationary installations')].index 
    indexNames1 = new_df[(new_df['main activity sector name'] == '21-99 All industrial installations (excl. combustion)')].index 
    new_df.drop(indexNames , inplace=True)
    new_df.drop(indexNames1 , inplace=True)
    #print(new_df.head())
    
    #tallentaa uuteen DataFrameen kaikki rivit, joissa sarakkeen 'year' lukuarvo on yhtäsuuri tai suurempi kuin 2010 ja yhtäsuuri tai pienempi kuin 2015.
    new_df['year"'] = new_df['year"'].str.replace('"','', regex=True)
    new_df = new_df[~new_df['year"'].str.startswith('Total')]
    
    #print(new_df.head(50))
    new_df['year"'] = new_df['year"'].astype(int)
    
    new_df=(new_df[(new_df['year"']>= 2010) & (new_df['year"']<=2015)])
    #print(new_df.head())
    
    #laskee uuteen DataFrameen kuinka paljon päästöjä kukin maa on tuottanut minäkin vuonna (laskee yhteen sarakkeen 'value' arvot, jotka on ryhmitelty sarakkeiden 'country_code' ja 'year' mukaan),
    uusi_Dataframe=new_df.groupby(["country_code", 'year"'], as_index=False)['value'].sum()
    uusi_Dataframe = pd.DataFrame(uusi_Dataframe)
    #print(uusi_Dataframe.head(53))
    
    #tallentaa uuteen DataFrameen kunkin maan (sarake 'country_code') toiseksi suurimmat päästöt (sarake 'value') ja päästön tuottamisvuoden (sarake 'year'),
    df1=uusi_Dataframe.groupby(['country_code'])[['value','year"']].apply(lambda x: x.nlargest(2, columns=['value'])) 
    #print(df1.head(5))
    
    dfuusi=df1.loc[df1.groupby('country_code')['value'].idxmin()]
    #print(dfuusi.head())
    
    #järjestää em. DataFramen rivit suurimmasta pienimpään sarakkeen 'value' mukaan,
    
    dfuusi = dfuusi.sort_values(by=['value'], ascending=False)
    #print(dfuusi.head())
    
    #nimeää sarakkeen 'country_code' sarakkeeksi 'ccode',
    dfuusi.reset_index(inplace=True)
    dfuusi.set_index('level_1', inplace=True)
    dfuusi.index.name = None
    #print(dfuusi.head())
    #print(list(dfuusi.columns))
    dfuusi.columns = ['ccode', 'value', 'year']
    #print(dfuusi.head())
    
    dfuusi = dfuusi[['ccode','year', 'value']]
    tulos=dfuusi.head()
    # Älä kirjoita muita print komentoja ennen tulos muuttujan tulostusta.
    print(tulos)

# Testaa funktiotasi:
url='https://student.labranet.jamk.fi/~huoptu/datananal_s20/kerta3/harjoitukset/ETS_Database_v38A.csv'
emissions(url)

    ccode  year         value
33     DE  2013  1.073414e+09
49     ES  2011  5.561922e+08
152    PL  2012  4.348634e+08
67     GB  2011  4.252068e+08
62     FR  2012  3.104471e+08